version: '3'
services:
  web:
    build: .
    command: ["gunicorn","notification_system.wsgi:application", "--workers=2", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
