# Generated by Django 4.2.5 on 2023-09-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification_ALL',
        ),
    ]
