# Generated by Django 4.2.5 on 2023-10-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_delete_notification_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
